name: tmdb
description: TmDB movies Flutter app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  bloc: ^9.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  auto_route: ^10.1.0
  envied: ^1.1.1
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  equatable: ^2.0.5
  pinput: ^4.0.0
  # Networking
  dio: ^5.4.0
  retrofit: ^4.0.3
  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.2
  # JSON Serialization
  json_annotation: ^4.9.0
  hive: ^2.2.3
  path_provider: ^2.0.15
  image_picker: ^1.1.2
  flutter_inappwebview: ^6.0.0
  just_the_tooltip: ^0.0.12
  dotted_line: ^3.2.2
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  google_fonts: ^6.1.0
  html: ^0.15.4
  video_player: ^2.6.0
  carousel_slider: ^5.0.0
  location: ^8.0.0
  geocoding: ^3.0.0
  flutter_screenutil: ^5.9.3
  internet_connection_checker_plus: ^2.0.0
  connectivity_plus: ^6.0.5
  lottie: ^3.1.2

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0
  build_runner: ^2.4.13
  auto_route_generator: 
  retrofit_generator: ^9.7.0
  json_serializable: ^6.8.0
  injectable_generator: ^2.4.1
  envied_generator: ^1.1.1


flutter:
  generate: true
  uses-material-design: true
